# Site settings
name: Kenneth
location: Hangzhou
school: ZJU
position: 前端开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown


theme: jekyll-theme-slate